### ISSUE TITLE
Bug #13 affichage/calcul panier 

### ISSUE THREAD

**Issue by Francis-Panzani** [Daruk32/Attable-Xampp#3]
Sprint 11 
Bug affichage/calcul prix panier
le total du panier n'est pas calculé ou afficher correctement

![image](https://user-images.githubusercontent.com/49025689/135728084-ba33f002-0d57-46ee-9805-a0ebeda4d078.png)

**Comment by Daruk32** [comment]
Problème impossible à recréer, origine ?
Fonctionnalité sans problème actuellement, résolution ???
